{"name": "Проверка увеличения счетчика \"Выполнено за сегодня\" при создании нового заказа", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.", "trace": "self = <tests.test_order_feed_page.TestCreateOrder object at 0x0000025053413550>, pages = <pages.UIWorkerWeb object at 0x00000250536C71B0>, login_user = <pages.UIWorkerWeb object at 0x00000250536C71B0>\nname_counter = 'Выполнено за сегодня', counter = ('xpath', '//p[text()=\"Выполнено за сегодня:\"]/following-sibling::p')\n\n    @pytest.mark.parametrize('name_counter, counter',\n                             [['Выполнено за все время', OrderFeedPageLocators.TOTAL_ORDER_COUNT],\n                              ['Выполнено за сегодня', OrderFeedPageLocators.DAILY_ORDER_COUNT]])\n    def test_orders_counter(self, pages, login_user, name_counter, counter):\n        allure.dynamic.title(f'Проверка увеличения счетчика \"{name_counter}\" при создании нового заказа')\n        pages.click_order_feed_button()\n        prev_counter_value = pages.get_total_order_count(counter)\n        pages.click_constructor_button()\n>       pages.create_order()\n\ntests\\test_order_feed_page.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\main_page.py:83: in create_order\n    order_id = self.get_order_id()\n               ^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.UIWorkerWeb object at 0x00000250536C71B0>, timeout = 10\n\n    @allure.step('Получить номер заказа')\n    def get_order_id(self, timeout=10):\n        self.check_element_displayed(MainPageLocators.ORDER_ID)\n        start_time = time.time()\n        while True:\n            order_id = self.get_element_text(MainPageLocators.ORDER_ID)\n            if order_id != '9999':\n                return order_id\n            if time.time() - start_time > timeout:\n>               raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\nE               Exception: Order ID did not update from \"9999\" within 10 seconds.\n\npages\\main_page.py:72: Exception"}, "steps": [{"name": "Кликнуть на кнопку \"Лента заказов\"", "status": "passed", "start": 1759620692410, "stop": 1759620692494}, {"name": "Получить количество заказов", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//p[text()=\"Выполнено за сегодня:\"]/following-sibling::p')"}], "start": 1759620692495, "stop": 1759620693527}, {"name": "Кликнуть на кнопку \"Конструктор\"", "status": "passed", "start": 1759620693527, "stop": 1759620693609}, {"name": "Создать заказ", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.\n", "trace": "  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 83, in create_order\n    order_id = self.get_order_id()\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 72, in get_order_id\n    raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\n"}, "steps": [{"name": "Добавить ингредиент в заказ", "status": "passed", "start": 1759620693609, "stop": 1759620694156}, {"name": "Кликнуть на кнопку \"Оформить заказ\"", "status": "passed", "start": 1759620694156, "stop": 1759620694218}, {"name": "Получить номер заказа", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.\n", "trace": "  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 72, in get_order_id\n    raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\n"}, "parameters": [{"name": "timeout", "value": "10"}], "start": 1759620694218, "stop": 1759620704237}], "start": 1759620693609, "stop": 1759620704237}], "parameters": [{"name": "driver", "value": "'firefox'"}, {"name": "name_counter", "value": "'Выполнено за сегодня'"}, {"name": "counter", "value": "('xpath', '//p[text()=\"Выполнено за сегодня:\"]/following-sibling::p')"}], "start": 1759620692410, "stop": 1759620704238, "uuid": "a40b3abb-222d-4ffc-9298-4d29cba5872f", "historyId": "fb09d1314fdd334f3ffd8cf368ccb9b6", "testCaseId": "53ca25f16112b04c2bced3d57ad97309", "fullName": "tests.test_order_feed_page.TestCreateOrder#test_orders_counter", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed_page"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-1UM8KQP"}, {"name": "thread", "value": "23004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed_page"}], "titlePath": ["tests", "test_order_feed_page.py", "TestCreateOrder"]}