{"name": "Проверка увеличения счетчика \"Выполнено за все время\" при создании нового заказа", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.", "trace": "self = <tests.test_order_feed_page.TestCreateOrder object at 0x00000250535A8380>, pages = <pages.UIWorkerWeb object at 0x0000025053A50940>, login_user = <pages.UIWorkerWeb object at 0x0000025053A50940>\nname_counter = 'Выполнено за все время', counter = ('xpath', '//p[text()=\"Выполнено за все время:\"]/following-sibling::p')\n\n    @pytest.mark.parametrize('name_counter, counter',\n                             [['Выполнено за все время', OrderFeedPageLocators.TOTAL_ORDER_COUNT],\n                              ['Выполнено за сегодня', OrderFeedPageLocators.DAILY_ORDER_COUNT]])\n    def test_orders_counter(self, pages, login_user, name_counter, counter):\n        allure.dynamic.title(f'Проверка увеличения счетчика \"{name_counter}\" при создании нового заказа')\n        pages.click_order_feed_button()\n        prev_counter_value = pages.get_total_order_count(counter)\n        pages.click_constructor_button()\n>       pages.create_order()\n\ntests\\test_order_feed_page.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\main_page.py:83: in create_order\n    order_id = self.get_order_id()\n               ^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.UIWorkerWeb object at 0x0000025053A50940>, timeout = 10\n\n    @allure.step('Получить номер заказа')\n    def get_order_id(self, timeout=10):\n        self.check_element_displayed(MainPageLocators.ORDER_ID)\n        start_time = time.time()\n        while True:\n            order_id = self.get_element_text(MainPageLocators.ORDER_ID)\n            if order_id != '9999':\n                return order_id\n            if time.time() - start_time > timeout:\n>               raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\nE               Exception: Order ID did not update from \"9999\" within 10 seconds.\n\npages\\main_page.py:72: Exception"}, "steps": [{"name": "Кликнуть на кнопку \"Лента заказов\"", "status": "passed", "start": 1759620669579, "stop": 1759620669665}, {"name": "Получить количество заказов", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', '//p[text()=\"Выполнено за все время:\"]/following-sibling::p')"}], "start": 1759620669665, "stop": 1759620670695}, {"name": "Кликнуть на кнопку \"Конструктор\"", "status": "passed", "start": 1759620670695, "stop": 1759620670783}, {"name": "Создать заказ", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.\n", "trace": "  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 83, in create_order\n    order_id = self.get_order_id()\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 72, in get_order_id\n    raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\n"}, "steps": [{"name": "Добавить ингредиент в заказ", "status": "passed", "start": 1759620670784, "stop": 1759620671360}, {"name": "Кликнуть на кнопку \"Оформить заказ\"", "status": "passed", "start": 1759620671361, "stop": 1759620671432}, {"name": "Получить номер заказа", "status": "broken", "statusDetails": {"message": "Exception: Order ID did not update from \"9999\" within 10 seconds.\n", "trace": "  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Zdravcity-User\\ya-practicum\\Diplom\\Diplom_3\\pages\\main_page.py\", line 72, in get_order_id\n    raise Exception(f'Order ID did not update from \"9999\" within {timeout} seconds.')\n"}, "parameters": [{"name": "timeout", "value": "10"}], "start": 1759620671432, "stop": 1759620681443}], "start": 1759620670784, "stop": 1759620681443}], "parameters": [{"name": "driver", "value": "'firefox'"}, {"name": "name_counter", "value": "'Выполнено за все время'"}, {"name": "counter", "value": "('xpath', '//p[text()=\"Выполнено за все время:\"]/following-sibling::p')"}], "start": 1759620669579, "stop": 1759620681444, "uuid": "2573ccca-0c33-474e-bec4-b086d66c1c07", "historyId": "134127ad44e3eaefab5093ed374a7e33", "testCaseId": "53ca25f16112b04c2bced3d57ad97309", "fullName": "tests.test_order_feed_page.TestCreateOrder#test_orders_counter", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed_page"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-1UM8KQP"}, {"name": "thread", "value": "23004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed_page"}], "titlePath": ["tests", "test_order_feed_page.py", "TestCreateOrder"]}